version: "3.8"
services:
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:15672"]
            interval: 30s
            timeout: 10s
            retries: 5
    fastapi:
        build:
            context: .
            dockerfile: Dockerfile.fastapi
        ports:
            - "8000:8000"
        depends_on:
            - rabbitmq

    celery_worker:
        build:
            context: .
            dockerfile: Dockerfile.celery
        depends_on:
            - rabbitmq
            - fastapi
    flower:
        image: mher/flower
        ports:
            - "5555:5555"
        environment:
            - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
            - FLOWER_PORT=5555
        depends_on:
            - rabbitmq
