FROM python:3.10
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY fastapi_server.py celery_module.py ./
CMD ["uvicorn", "fastapi_server:app", "--host", "0.0.0.0", "--port", "8000"]