FROM python:3.10
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN python -m spacy download en_core_web_md 
COPY celery_module.py ./
CMD ["celery", "-A", "celery_module", "worker", "--loglevel=info"]
